name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - 7.4
env:
  PHP_VERSION: '7.4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MYGITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker buildx build --push --tag ghcr.io/${{ github.repository_owner }}/apache2-4-php7.4-composer:${{ github.sha }} --target lzarus_swagger .
          docker buildx build --push --tag ghcr.io/${{ github.repository_owner }}/apache2-4-php7.4-composer:swagger-latest --target lzarus_swagger .

      - name: Build and push Docker image for Azure target
        run: |
          docker buildx build --push --build-arg PHP_VERSION=${{ env.PHP_VERSION }} --tag ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/apache2.4-php${{ env.PHP_VERSION }}-composer:latest --target lzarus_msaz .

      - name: Cleanup Docker Buildx
        run: docker buildx prune --all

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for Swagger target on Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apache2.4-php${{ env.PHP_VERSION }}-composer:swagger-latest