name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ vars.PHP_VERSION }} 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MYGITHUB_TOKEN }}

      - name: Build and push Docker image for Swagger target on GHCR and Docker Hub
        run: |
          docker buildx build --push --build-arg PHP_VERSION=${{ env.PHP_VERSION }} \
          -t ghcr.io/${{ github.repository_owner }}/apache-php-composer:${{ github.sha }} \
          -t ghcr.io/${{ github.repository_owner }}/apache-php-composer:${{ env.PHP_VERSION }}-swagger \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/apache-php-composer:${{ env.PHP_VERSION }}-swagger --target lzarus_swagger .

      - name: Build and push Docker image for Azure target on GHCR and Docker Hub
        run: |
          docker buildx build --push --build-arg PHP_VERSION=${{ env.PHP_VERSION }} \
          -t ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/apache-php-composer:${{ env.PHP_VERSION }}-latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/apache-php-composer:${{ env.PHP_VERSION }}-latest --target lzarus_msaz .

      - name: Build and push Docker image for framework laravel target on GHCR and Docker Hub
        run: |
          docker buildx build --push --build-arg PHP_VERSION=${{ env.PHP_VERSION }} \
          -t ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/apache-php-composer:${{ env.PHP_VERSION }}-laravel \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/apache-php-composer:${{ env.PHP_VERSION }}-laravel --target lzarus_laravel .

      - name: Cleanup Docker Buildx
        run: docker buildx prune --all
